export type WorkCategory = "painting" | "works-on-paper" | "textile";

export type Work = {
  slug: string;
  title: string;
  series?: string;
  medium: string;
  dimensions: string;
  year: number;
  category: WorkCategory;
  image: string;
  instagramPost: string;
  featured?: boolean;
};

const IG = "https://www.instagram.com/isabella_billiet";

export const works: Work[] = [
  {
    slug: "tussen-het-gras",
    title: "Tussen het gras",
    series: "Recente werken",
    medium: "Oil on linen canvas",
    dimensions: "23 × 29 cm",
    year: 2026,
    category: "painting",
    image: "/images/tussen-het-gras.webp",
    instagramPost: IG,
    featured: true,
  },
  {
    slug: "recente-1",
    title: "Recente werken I",
    series: "Recente werken",
    medium: "Oil on panel",
    dimensions: "—",
    year: 2026,
    category: "painting",
    image: "/images/recente-1.webp",
    instagramPost: IG,
    featured: true,
  },
  {
    slug: "recente-2",
    title: "Recente werken II",
    series: "Recente werken",
    medium: "Oil on panel",
    dimensions: "—",
    year: 2026,
    category: "painting",
    image: "/images/recente-2.webp",
    instagramPost: IG,
    featured: true,
  },
  {
    slug: "magnolia-1",
    title: "Magnolia I",
    series: "Magnolia",
    medium: "Oil on wooden panel — work in progress",
    dimensions: "13 × 14.5 cm",
    year: 2026,
    category: "painting",
    image: "/images/magnolia-1.webp",
    instagramPost: IG,
    featured: true,
  },
  {
    slug: "magnolia-2",
    title: "Magnolia II",
    series: "Magnolia",
    medium: "Oil on wooden panel — work in progress",
    dimensions: "13 × 14.5 cm",
    year: 2026,
    category: "painting",
    image: "/images/magnolia-2.webp",
    instagramPost: IG,
  },
  {
    slug: "magnolia-3",
    title: "Magnolia III",
    series: "Magnolia",
    medium: "Oil on wooden panel — work in progress",
    dimensions: "13 × 14.5 cm",
    year: 2026,
    category: "painting",
    image: "/images/magnolia-3.webp",
    instagramPost: IG,
  },
  {
    slug: "galaxy-1",
    title: "Galaxy I",
    series: "Galaxy",
    medium: "Acrylic on canvas",
    dimensions: "15 × 21 cm",
    year: 2018,
    category: "painting",
    image: "/images/galaxy-1.webp",
    instagramPost: IG,
  },
  {
    slug: "galaxy-2",
    title: "Galaxy II",
    series: "Galaxy",
    medium: "Acrylic on canvas",
    dimensions: "15 × 21 cm",
    year: 2018,
    category: "painting",
    image: "/images/galaxy-2.webp",
    instagramPost: IG,
  },
  {
    slug: "galaxy-3",
    title: "Galaxy III",
    series: "Galaxy",
    medium: "Acrylic on canvas",
    dimensions: "15 × 21 cm",
    year: 2018,
    category: "painting",
    image: "/images/galaxy-3.webp",
    instagramPost: IG,
  },
  {
    slug: "galaxy-4",
    title: "Galaxy IV",
    series: "Galaxy",
    medium: "Acrylic on canvas",
    dimensions: "15 × 21 cm",
    year: 2018,
    category: "painting",
    image: "/images/galaxy-4.webp",
    instagramPost: IG,
  },
  {
    slug: "whispers-green-watercolor",
    title: "Whispers of the Green I",
    series: "Whispers of the Green",
    medium: "Watercolor & pencil on Canson paper",
    dimensions: "15 × 20 cm",
    year: 2026,
    category: "works-on-paper",
    image: "/images/whispers-green-watercolor.webp",
    instagramPost: IG,
    featured: true,
  },
  {
    slug: "whispers-green-watercolor-2",
    title: "Whispers of the Green II",
    series: "Whispers of the Green",
    medium: "Watercolor & pencil on Canson paper",
    dimensions: "15 × 20 cm",
    year: 2026,
    category: "works-on-paper",
    image: "/images/whispers-green-watercolor-2.webp",
    instagramPost: IG,
  },
  {
    slug: "whispers-green-watercolor-3",
    title: "Whispers of the Green III",
    series: "Whispers of the Green",
    medium: "Watercolor & pencil on Canson paper",
    dimensions: "15 × 20 cm",
    year: 2026,
    category: "works-on-paper",
    image: "/images/whispers-green-watercolor-3.webp",
    instagramPost: IG,
  },
  {
    slug: "whispers-green-watercolor-4",
    title: "Whispers of the Green IV",
    series: "Whispers of the Green",
    medium: "Watercolor & pencil on Canson paper",
    dimensions: "15 × 20 cm",
    year: 2026,
    category: "works-on-paper",
    image: "/images/whispers-green-watercolor-4.webp",
    instagramPost: IG,
  },
  {
    slug: "werken-op-papier-1",
    title: "Werken op papier I",
    series: "Werken op papier",
    medium: "On paper",
    dimensions: "—",
    year: 2026,
    category: "works-on-paper",
    image: "/images/werken-op-papier-1.webp",
    instagramPost: IG,
    featured: true,
  },
  {
    slug: "werken-op-papier-2",
    title: "Werken op papier II",
    series: "Werken op papier",
    medium: "On paper",
    dimensions: "—",
    year: 2026,
    category: "works-on-paper",
    image: "/images/werken-op-papier-2.webp",
    instagramPost: IG,
  },
  {
    slug: "werken-op-papier-3",
    title: "Werken op papier III",
    series: "Werken op papier",
    medium: "On paper",
    dimensions: "—",
    year: 2026,
    category: "works-on-paper",
    image: "/images/werken-op-papier-3.webp",
    instagramPost: IG,
  },
  {
    slug: "werken-op-papier-4",
    title: "Werken op papier IV",
    series: "Werken op papier",
    medium: "On paper",
    dimensions: "—",
    year: 2026,
    category: "works-on-paper",
    image: "/images/werken-op-papier-4.webp",
    instagramPost: IG,
  },
  {
    slug: "werken-op-papier-5",
    title: "Werken op papier V",
    series: "Werken op papier",
    medium: "On paper",
    dimensions: "—",
    year: 2026,
    category: "works-on-paper",
    image: "/images/werken-op-papier-5.webp",
    instagramPost: IG,
  },
  {
    slug: "werken-op-papier-6",
    title: "Werken op papier VI",
    series: "Werken op papier",
    medium: "On paper",
    dimensions: "—",
    year: 2026,
    category: "works-on-paper",
    image: "/images/werken-op-papier-6.webp",
    instagramPost: IG,
  },
  {
    slug: "weavings",
    title: "Weavings",
    series: "Weavings",
    medium: "Acrylic on linen — textile exploration",
    dimensions: "100 × 120 cm",
    year: 2019,
    category: "textile",
    image: "/images/weavings.webp",
    instagramPost: IG,
    featured: true,
  },
  {
    slug: "weavings-2",
    title: "Weavings II",
    series: "Weavings",
    medium: "Acrylic on linen — textile exploration",
    dimensions: "—",
    year: 2019,
    category: "textile",
    image: "/images/weavings-2.webp",
    instagramPost: IG,
  },
  {
    slug: "work-in-progress",
    title: "Work in Progress",
    series: "Nature, Light & Shadow",
    medium: "On paper — work in progress",
    dimensions: "—",
    year: 2026,
    category: "works-on-paper",
    image: "/images/work-in-progress.webp",
    instagramPost: `${IG}/p/CvX0XZLNCBv/`,
    featured: true,
  },
  {
    slug: "plants",
    title: "Plants",
    series: "Botanical Studies",
    medium: "Watercolor & gouache on paper",
    dimensions: "—",
    year: 2025,
    category: "works-on-paper",
    image: "/images/plants.webp",
    instagramPost: `${IG}/p/DUrAilziLzw/`,
    featured: true,
  },
  {
    slug: "florals",
    title: "Florals",
    series: "Botanical Studies",
    medium: "Watercolor & gouache on paper",
    dimensions: "—",
    year: 2025,
    category: "works-on-paper",
    image: "/images/florals.webp",
    instagramPost: `${IG}/p/DVwi1aViFSQ/`,
  },
  {
    slug: "whispers-green-gouache-1",
    title: "Whispers of the Green — Gouache I",
    series: "Whispers of the Green",
    medium: "Gouache on Arches paper",
    dimensions: "76 × 56 cm",
    year: 2025,
    category: "works-on-paper",
    image: "/images/whispers-green-gouache-1.webp",
    instagramPost: IG,
    featured: true,
  },
  {
    slug: "whispers-green-gouache-2",
    title: "Whispers of the Green — Gouache II",
    series: "Whispers of the Green",
    medium: "Gouache on Arches paper",
    dimensions: "76 × 56 cm",
    year: 2025,
    category: "works-on-paper",
    image: "/images/whispers-green-gouache-2.webp",
    instagramPost: IG,
  },
  {
    slug: "whispers-green-gouache-3",
    title: "Whispers of the Green — Gouache III",
    series: "Whispers of the Green",
    medium: "Gouache on Arches paper",
    dimensions: "76 × 56 cm",
    year: 2025,
    category: "works-on-paper",
    image: "/images/whispers-green-gouache-3.webp",
    instagramPost: IG,
  },
  {
    slug: "whispers-green-gouache-4",
    title: "Whispers of the Green — Gouache IV",
    series: "Whispers of the Green",
    medium: "Gouache on Arches paper",
    dimensions: "76 × 56 cm",
    year: 2025,
    category: "works-on-paper",
    image: "/images/whispers-green-gouache-4.webp",
    instagramPost: IG,
  },
  {
    slug: "traces",
    title: "Traces I",
    series: "Traces",
    medium: "Gouache, pastel & pencil on paper",
    dimensions: "—",
    year: 2023,
    category: "works-on-paper",
    image: "/images/traces.webp",
    instagramPost: IG,
  },
  {
    slug: "traces-2",
    title: "Traces II",
    series: "Traces",
    medium: "Gouache, pastel & pencil on paper",
    dimensions: "—",
    year: 2023,
    category: "works-on-paper",
    image: "/images/traces-2.webp",
    instagramPost: IG,
  },
  {
    slug: "traces-3",
    title: "Traces III",
    series: "Traces",
    medium: "Gouache, pastel & pencil on paper",
    dimensions: "—",
    year: 2023,
    category: "works-on-paper",
    image: "/images/traces-3.webp",
    instagramPost: IG,
  },
  {
    slug: "breathing-in-breathing-out",
    title: "Breathing in & breathing out",
    medium: "Acrylic on canvas",
    dimensions: "24 × 30 cm",
    year: 2022,
    category: "painting",
    image: "/images/breathing-in-breathing-out.webp",
    instagramPost: `${IG}/p/CzwS5VzNjoi/`,
    featured: true,
  },
  {
    slug: "golden-morning-light",
    title: "Golden Morning Light",
    series: "Golden Morning Light",
    medium: "Acrylic and oil on linen canvas",
    dimensions: "50 × 60 cm",
    year: 2021,
    category: "painting",
    image: "/images/golden-morning-light.webp",
    instagramPost: IG,
  },
  {
    slug: "vagues-gigaro",
    title: "Vagues, Gigaro",
    series: "World Oceans Day",
    medium: "Watercolor on paper",
    dimensions: "—",
    year: 2021,
    category: "works-on-paper",
    image: "/images/vagues-gigaro.webp",
    instagramPost: `${IG}/p/CP2ixQIBdqV/`,
  },
  {
    slug: "watercolor-study",
    title: "Watercolor Study",
    medium: "Watercolor on paper",
    dimensions: "—",
    year: 2020,
    category: "works-on-paper",
    image: "/images/watercolor-study.webp",
    instagramPost: IG,
  },
  {
    slug: "water-energy",
    title: "Water Energy",
    medium: "Oil on linen canvas",
    dimensions: "24 × 30 cm",
    year: 2020,
    category: "painting",
    image: "/images/water-energy.webp",
    instagramPost: IG,
  },
  {
    slug: "water-in-movement-1",
    title: "Water in Movement I",
    series: "Water in Movement",
    medium: "Watercolor on Arches cotton paper",
    dimensions: "—",
    year: 2019,
    category: "works-on-paper",
    image: "/images/water-in-movement-1.webp",
    instagramPost: IG,
  },
  {
    slug: "water-in-movement-1b",
    title: "Water in Movement Ib",
    series: "Water in Movement",
    medium: "Watercolor on Arches cotton paper",
    dimensions: "—",
    year: 2019,
    category: "works-on-paper",
    image: "/images/water-in-movement-1b.webp",
    instagramPost: IG,
  },
  {
    slug: "water-in-movement-1c",
    title: "Water in Movement Ic",
    series: "Water in Movement",
    medium: "Watercolor on Arches cotton paper",
    dimensions: "—",
    year: 2019,
    category: "works-on-paper",
    image: "/images/water-in-movement-1c.webp",
    instagramPost: IG,
  },
  {
    slug: "water-in-movement-2",
    title: "Water in Movement II",
    series: "Water in Movement",
    medium: "Watercolor",
    dimensions: "—",
    year: 2019,
    category: "works-on-paper",
    image: "/images/water-in-movement-2.webp",
    instagramPost: IG,
  },
  {
    slug: "galaxy",
    title: "Galaxy",
    series: "Galaxy",
    medium: "Acrylic on linen canvas",
    dimensions: "80 × 120 cm",
    year: 2018,
    category: "painting",
    image: "/images/galaxy.webp",
    instagramPost: IG,
  },
];

export const exhibitionImages = [
  {
    slug: "exhibition-1",
    image: "/images/exhibition-1.webp",
    caption: "Studio view",
  },
  {
    slug: "exhibition-2",
    image: "/images/exhibition-2.webp",
    caption: "Works on paper",
  },
  {
    slug: "exhibition-3",
    image: "/images/exhibition-3.webp",
    caption: "Studio / works overview",
  },
  {
    slug: "exhibition-4",
    image: "/images/exhibition-4.webp",
    caption: "Exhibition install",
  },
  {
    slug: "exhibition-5",
    image: "/images/exhibition-5.webp",
    caption: "Gallery view",
  },

  {
    slug: "studio-view-01",
    image: "/images/studio-view-01.webp",
    caption: "Studio view",
  },
  {
    slug: "studio-view-02",
    image: "/images/studio-view-02.webp",
    caption: "Studio view",
  },
  {
    slug: "studio-view-03",
    image: "/images/studio-view-03.webp",
    caption: "Studio / works overview",
  },
  {
    slug: "studio-view-04",
    image: "/images/studio-view-04.webp",
    caption: "Studio view",
  },
  {
    slug: "studio-view-05",
    image: "/images/studio-view-05.webp",
    caption: "Studio view",
  },
  {
    slug: "studio-view-06",
    image: "/images/studio-view-06.webp",
    caption: "Studio / works overview",
  },
  {
    slug: "studio-view-07",
    image: "/images/studio-view-07.webp",
    caption: "Studio view",
  },
  {
    slug: "studio-view-08",
    image: "/images/studio-view-08.webp",
    caption: "Studio view",
  },
  {
    slug: "studio-view-09",
    image: "/images/studio-view-09.webp",
    caption: "Studio view",
  },
  {
    slug: "exhibition-view-01",
    image: "/images/exhibition-view-01.webp",
    caption: "Exhibition install",
  },
  {
    slug: "exhibition-view-02",
    image: "/images/exhibition-view-02.webp",
    caption: "Gallery view",
  },
  {
    slug: "exhibition-view-03",
    image: "/images/exhibition-view-03.webp",
    caption: "Exhibition install",
  },
  {
    slug: "exhibition-view-04",
    image: "/images/exhibition-view-04.webp",
    caption: "Gallery view",
  },
  {
    slug: "exhibition-view-05",
    image: "/images/exhibition-view-05.webp",
    caption: "Exhibition install",
  },
];

export const exhibitions = [
  {
    year: 2025,
    title: "Group exhibition at Delen Private Bank",
    location: "BP tower, Antwerp, Belgium",
    period: "Aug 2025 — Aug 2026",
    current: true,
  },
  {
    year: 2026,
    title: "Artist residency — Convento de Mértola",
    location: "Convento de São Francisco, Mértola, Portugal",
    period: "May 2026",
  },
  {
    year: 2025,
    title: "Open Studios Tarifa Facinas",
    location: "Tarifa, Spain — duo with Gaëtane Hermans",
    period: "Sep 18 — 21, 2025",
  },
  {
    year: 2025,
    title: "Mirrors of Reality",
    location: "Campo Santo, Ghent, Belgium",
    period: "May 28 — Jun 1, 2025",
  },
  {
    year: 2024,
    title: "Offspace",
    location: "Gallery Ben Benaouisse, Ghent, Belgium",
    period: "Mar 2 — 3, 2024",
  },
  {
    year: 2024,
    title: "Vitrines d'Amour",
    location: "Ghent, Belgium",
    period: "Feb 9 — 18, 2024",
  },
  {
    year: 2023,
    title: "Aqua di Sale",
    location: "Ziso Art, Gallery Charlotte van Lorreinen, Tervuren",
    period: "Sep 29 — Oct 8, 2023",
  },
  {
    year: 2023,
    title: "Vitrines d'Amour",
    location: "Bulthaup, Ghent, Belgium",
    period: "Feb 5 — Mar 31, 2023",
  },
  {
    year: 2022,
    title: "Group exhibition, Ferme Dehon",
    location: "Frasnes-lez-Buisenal, Belgium",
    period: "May 28 — 29 & Jun 4 — 6, 2022",
  },
  {
    year: 2020,
    title: "Vitrines d'Amour",
    location: "Ghent, Belgium",
    period: "Feb 1 — 14, 2020",
  },
  {
    year: 2019,
    title: "Underground",
    location: "Ghent, Belgium",
    period: "Dec 14 — 15, 2019",
  },
  {
    year: 2019,
    title: "Open Atelier",
    location: "Predikherenlei, Ghent, Belgium",
    period: "May 2019",
  },
  {
    year: 2019,
    title: "Vitrines d'Amour",
    location: "Ghent, Belgium",
    period: "Feb 1 — 14, 2019",
  },
  {
    year: 2018,
    title: "Nucleo Open Ateliers #12",
    location: "Ghent, Belgium",
    period: "Oct 2018",
  },
];

export function getWorkBySlug(slug: string): Work | undefined {
  return works.find((work) => work.slug === slug);
}

export function getFeaturedWorks(): Work[] {
  return works.filter((work) => work.featured);
}

export function getRecentWorks(limit = 4): Work[] {
  return [...works].sort((a, b) => b.year - a.year).slice(0, limit);
}
